cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'awscli'
brew 'coreutils'
brew 'git'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'python3'
brew 'unrar'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'emacs'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'slack'

